# Generated by Django 5.2.7 on 2025-10-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_rand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'News Article', 'verbose_name_plural': 'News Articles'},
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, separated by commas', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title', max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='body_txt',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_txt',
            field=models.TextField(verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.TextField(default='', help_text='Separate tags with commas'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-id', 'act'], name='news_news_id_4d0007_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug'], name='news_news_slug_915ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['catid', 'act'], name='news_news_catid_b73387_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-show'], name='news_news_show_f1dc89_idx'),
        ),
    ]
