# Generated by Django 5.2.7 on 2025-10-27 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(help_text='Base32 encoded secret key', max_length=100)),
                ('is_enabled', models.BooleanField(default=False, help_text='Is 2FA enabled for this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twofa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two-Factor Authentication',
                'verbose_name_plural': 'Two-Factor Authentications',
                'db_table': 'twofa_auth',
            },
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('twofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='twofa.twofactorauth')),
            ],
            options={
                'verbose_name': 'Backup Code',
                'verbose_name_plural': 'Backup Codes',
                'db_table': 'twofa_backup_codes',
                'indexes': [models.Index(fields=['code'], name='twofa_backu_code_5bae02_idx'), models.Index(fields=['twofa', 'is_used'], name='twofa_backu_twofa_i_26213e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(help_text='Was the verification successful')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('totp', 'TOTP Code'), ('backup', 'Backup Code')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twofa_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two-Factor Log',
                'verbose_name_plural': 'Two-Factor Logs',
                'db_table': 'twofa_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='twofa_logs_user_id_0e1819_idx'), models.Index(fields=['success', '-timestamp'], name='twofa_logs_success_ebdbad_idx')],
            },
        ),
    ]
