# Generated by Django 5.2.7 on 2025-10-27 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorlog',
            name='method',
            field=models.CharField(choices=[('totp', 'TOTP Code'), ('backup', 'Backup Code'), ('email', 'Email Code')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Code',
                'verbose_name_plural': 'Email Verification Codes',
                'db_table': 'twofa_email_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='twofa_email_token_338803_idx'), models.Index(fields=['user', '-created_at'], name='twofa_email_user_id_ff491c_idx')],
            },
        ),
    ]
